
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishnan
 */
public class flaps extends javax.swing.JFrame {

    /**
     * Creates new form flaps
     */
    public flaps() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        jLabel18.setText("jLabel18");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 190, 18, 19);

        jButton2.setText("Jump");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 496, 90, 23);

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(102, 0, 38, 230);

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(102, 291, 38, 228);

        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3);
        jLabel3.setBounds(167, 0, 38, 238);

        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel4);
        jLabel4.setBounds(167, 301, 38, 218);

        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel5);
        jLabel5.setBounds(223, 0, 38, 230);

        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel6);
        jLabel6.setBounds(223, 289, 38, 230);

        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel7);
        jLabel7.setBounds(271, 0, 38, 230);

        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel8);
        jLabel8.setBounds(271, 289, 38, 230);

        jLabel9.setText("jLabel9");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9);
        jLabel9.setBounds(327, 0, 38, 240);

        jLabel10.setText("jLabel1");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel10);
        jLabel10.setBounds(327, 299, 38, 220);

        jLabel11.setText("jLabel2");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel11);
        jLabel11.setBounds(380, 0, 38, 220);

        jLabel12.setText("jLabel3");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel12);
        jLabel12.setBounds(383, 289, 38, 230);

        jLabel13.setText("jLabel4");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel13);
        jLabel13.setBounds(431, 0, 38, 220);

        jLabel14.setText("jLabel5");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel14);
        jLabel14.setBounds(431, 293, 38, 226);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Game Over!");
        jLabel15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel15KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 530, 520);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 453, 50, 10);

        jButton4.setText("Play again");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(0, 470, 100, 23);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("No of rounds");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 10, 90, 20);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 30, 0, 0);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("completed: 0");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 30, 90, 15);

        jButton5.setText("<html>Go to instructions<br> page");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(400, 240, 130, 30);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flapback.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(0, 0, 790, 550);

        setBounds(0, 0, 546, 557);
    }// </editor-fold>//GEN-END:initComponents
void pillars(int r1,int r3,int r5,int r7,int r9,int r11,int r13){
    if(r1==0){
    jLabel1.setVisible(false);
    jLabel2.setVisible(false);
}    
if(r3==0){
    jLabel3.setVisible(false);
    jLabel4.setVisible(false);
}    
if(r5==0){
    jLabel5.setVisible(false);
    jLabel6.setVisible(false);
}    
if(r7==0){
    jLabel7.setVisible(false);
    jLabel8.setVisible(false);
}
if(r9==0){
    jLabel9.setVisible(false);
    jLabel10.setVisible(false);
}    
if(r11==0){
    jLabel11.setVisible(false);
    jLabel12.setVisible(false);
}
if(r13==0){
    jLabel13.setVisible(false);
    jLabel14.setVisible(false);
}
}
Timer t;
int x=0, y=200;
int i=-5, j=0, k=0;
Random r=new Random();
int r1=r.nextInt(3), r3=r.nextInt(3), r5=r.nextInt(3), r7=r.nextInt(3), r9=r.nextInt(3),r11=r.nextInt(3),r13=r.nextInt(3);
int l1, l2, l3, l4, l5, l6, l7, l8, l9, l10, l11, l12, l13, l14;
int m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11, m12, m13, m14;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jLabel15.setVisible(false);
jButton5.setVisible(false);
l1=jLabel1.getHeight();
l2=jLabel2.getLocation().y;
l3=jLabel3.getHeight();
l4=jLabel4.getLocation().y;
l5=jLabel5.getHeight();
l6=jLabel6.getLocation().y;
l7=jLabel7.getHeight();
l8=jLabel8.getLocation().y;
l9=jLabel9.getHeight();
l10=jLabel10.getLocation().y;
l11=jLabel11.getHeight();
l12=jLabel12.getLocation().y;
l13=jLabel13.getHeight();
l14=jLabel14.getLocation().y;

m1=jLabel1.getLocation().x;
m3=jLabel3.getLocation().x;
m5=jLabel5.getLocation().x;
m7=jLabel7.getLocation().x;
m9=jLabel9.getLocation().x;
m11=jLabel11.getLocation().x;
m13=jLabel13.getLocation().x;
if(j==1)t.stop();
i=-5; k=0;
j=1;
ActionListener action;
        action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                x+=5;
                y+=2*i;
                jButton1.setLocation(x,y);
                i++;
                if(r1!=0){
                    if(((x>=m1-18)&&(x<=m1+45))&&((y<=l1)||(y>=l2-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                } 
                if(r3!=0){
                    if(((x>=m3-18)&&(x<=m3+45))&&((y<=l3)||(y>=l4-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                }    
                if(r5!=0){
                    if(((x>=m5-18)&&(x<=m5+45))&&((y<=l5)||(y>=l6-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                }
                if(r7!=0){
                    if(((x>=m7-18)&&(x<=m7+45))&&((y<=l7)||(y>=l8-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                }  
                if(r9!=0){
                    if(((x>=m9-18)&&(x<=m9+45))&&((y<=l9)||(y>=l10-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                }
                if(r11!=0){
                    if(((x>=m11-18)&&(x<=m11+45))&&((y<=l11)||(y>=l12-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                }    
                if(r13!=0){
                    if(((x>=m13-18)&&(x<=m13+45))&&((y<=l13)||(y>=l14-15))){
                        t.stop();jButton2.setEnabled(false);
                        jButton1.doClick(); jButton5.setVisible(true);
                    }    
                }
                if(x>=530){k=1;
                    t.stop();jButton2.setEnabled(false);
                    jButton1.doClick();
                }    
            }
        };
t = new Timer(100, action);
t.setDelay(60);
t.setRepeats(true);
t.start();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
pillars(r1,r3,r5,r7,r9,r11,r13);
jLabel15.setVisible(false);
jButton3.setVisible(false);
jButton4.setVisible(false);
jLabel2.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jLabel1.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel3.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel4.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jLabel5.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel6.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jLabel7.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel8.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jLabel9.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel10.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jLabel11.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel12.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jLabel13.setIcon(new ImageIcon("F:\\Java Project\\src\\dpill.jpg"));
jLabel14.setIcon(new ImageIcon("F:\\Java Project\\src\\pillar.jpg"));
jButton1.setIcon(new ImageIcon("F:\\Java Project\\src\\bird.jpg"));
    }//GEN-LAST:event_formWindowOpened
Timer t1, t2; int m=0, p=4, round=1, score; 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
m=0;
ActionListener action;
        action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jLabel15.setVisible(true);
                if(k==1){
                    jLabel15.setText("Round "+round+" completed");
                    jLabel19.setText("completed: "+round);
                }    
                else{score= (round-1)*5;
                    jLabel15.setText("Game Over!");
                    try{
                        Class.forName("java.sql.Driver");
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javaproject","root","mysql");
                        Statement st = con.createStatement();
                        String check = "select highscore from flappybird where username = '"+loginform.user+"';";
                        ResultSet rs = st.executeQuery(check);
                        rs.next();
                        if(score>rs.getInt(1)){
                            String add = "update flappybird set highscore = "+score+" where username = '"+loginform.user+"';";
                            st.executeUpdate(add);
                        }
                    }
                    catch(Exception E){
                        System.out.print(E.getMessage());
                    }
                }
                y+=5;
                jButton1.setLocation(x,y);
                if(y>=520){round++;
                    t1.stop();
                    x=0; y=200;
                    jButton1.setLocation(x,y);
                    r1=r.nextInt(3);r3=r.nextInt(3);r5=r.nextInt(3);r7=r.nextInt(3);r9=r.nextInt(3);r11=r.nextInt(3);r13=r.nextInt(3);
                    j=0;                
                    if(k==0)jLabel15.setText("Your score is "+score);
                    if(k==1){jButton3.doClick();
                    
                    }
                    else jButton4.setVisible(true);
                }    
                    
            }
        };
t1 = new Timer(100, action);
t1.setDelay(60);
t1.setRepeats(true);
t1.start();     
jLabel1.setVisible(true);
jLabel2.setVisible(true);
jLabel3.setVisible(true);
jLabel4.setVisible(true);
jLabel5.setVisible(true);
jLabel6.setVisible(true);
jLabel7.setVisible(true);
jLabel8.setVisible(true); 
jLabel9.setVisible(true);
jLabel10.setVisible(true);
jLabel11.setVisible(true);
jLabel12.setVisible(true);
jLabel13.setVisible(true);
jLabel14.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
pillars(r1,r3,r5,r7,r9,r11,r13);
p=4;
    ActionListener action;
        action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                p--;
                jLabel15.setText("Next round starts in "+p+" seconds");
                if(p==0){
                    t2.stop();
                    jButton2.setEnabled(true);
                    jButton2.doClick();
                }    
                    
            }
        };
    t2 = new Timer(100, action);
    t2.setDelay(1000);
    t2.setRepeats(true);
    t2.start();              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
r1=r.nextInt(3);r3=r.nextInt(3);r5=r.nextInt(3);r7=r.nextInt(3);r9=r.nextInt(3);r11=r.nextInt(3);r13=r.nextInt(3);
pillars(r1,r3,r5,r7,r9,r11,r13);
jButton2.setEnabled(true);
jLabel15.setVisible(false);
jButton4.setVisible(false);
round =1;
jLabel19.setText("completed: 0");
jButton5.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel15KeyPressed
    }//GEN-LAST:event_jLabel15KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
new flappybird().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flaps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flaps().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
