
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishnan
 */
public class movebtnn extends javax.swing.JFrame {
 

    /**
     * Creates new form movebtnn
     */
    public movebtnn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(453, 11, 33, 14);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(492, 11, 32, 14);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(412, 11, 35, 14);

        jLabel4.setText("Lives");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(362, 11, 40, 14);

        jLabel5.setText("Coins:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 11, 41, 14);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(69, 11, 23, 14);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(98, 11, 25, 14);

        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 102, 42, 12);

        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 60, 22, 9);

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 445, 57, 23);

        jButton6.setText("Go to instruction page");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(63, 445, 160, 23);

        jButton7.setText("Restart");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(230, 440, 69, 23);

        jButton5.setText("Play again");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 440, 100, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("GAME OVER");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 410, 115, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose difficulty level"));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Easy");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Medium");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Hard");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 359, 173, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/land.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 610, 430);

        setBounds(0, 0, 640, 517);
    }// </editor-fold>//GEN-END:initComponents
Timer t2; float slope; double fact;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(m==1)
    t2.stop();
ActionListener action;
action = new ActionListener(){ @Override
    public void actionPerformed(ActionEvent e){} };
if(m==1){
    action = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            y+=k-5;       
            jButton1.setLocation(x,y);
            k++;
        }
    };
}

int m1 = r.nextInt(2);
int m2 = r.nextInt(2);
int md = r.nextInt(10);
slope = (float)(m1) + (float)md/10;
y1=r.nextInt(100);
jButton1.setIcon(new ImageIcon("F:\\Java Project\\src\\kuruvi.jpg"));
if((slope==0)||(a==2)){
    y1 = r.nextInt(200)+100;
} 
fact = (r.nextInt(50)+20);
if(m==0){
    y = (int)y1;
    action = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(a==0){
                x+=8;
                y1 += 5*slope;
                y =Math.round(y1);
                jButton1.setLocation(x,y);
            }    
            if(a==1){
                y+=(2*l+1)/5;    
                x+=10;
                jButton1.setLocation(x,y);
                l++;
            }  
            if(a==2){
                x+=8;
                y3 =(double)y1;
                double ref = y3;
                y3 = ref + Math.sin(x)*fact;
                y1 = (float)y3;
                y = Math.round(y1);
                jButton1.setLocation(x,y);
            }
            if(((y>=550)||(x>600))&&(m==0)){
                j=0; m=0; k=0; x=0; l=0;
                y2=60; x2=600;
                jButton3.setLocation(600,60); 
                t2.stop();
                i++;
                if(ref<i)JOptionPane.showMessageDialog(null,"You missed it\nYou lost a life\n\nClick OK to continue");
                jButton1.doClick();
            }
        }
    };
}

t2 = new Timer(100, action);
t2.setDelay(100);
t2.setRepeats(true);
t2.start();
    }//GEN-LAST:event_jButton1ActionPerformed
Timer t;
Random r=new Random();
int i=0, j=0, m=0, k=0, l=0, score=0, n=0, ref=0, a=2;
int x=0, y=0, y2=60, x2=600;
float y1= r.nextInt(100);
double y3;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int b=0;
if((jRadioButton1.isSelected()==false)&&(jRadioButton2.isSelected()==false)&&(jRadioButton3.isSelected()==false)){
    JOptionPane.showMessageDialog(this,"Please choose a difficulty level");
    b++;
}    
if(b==0){
    jButton7.setVisible(true);
    jButton6.setVisible(false);
    jPanel2.setVisible(false);
    jButton2.setVisible(false);
    jButton1.doClick();
}
    }//GEN-LAST:event_jButton2ActionPerformed
String[] difficulty = {"Easy","Medium","Hard"};
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
m++;n=0;
ActionListener action;
action = new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        if(n==0){y2+=(2*j+1)/5;    
            x2-=10;
            jButton3.setLocation(x2,y2);
            j++;
        }  
        if((y>=550)||(x>600)||(y2>600)){
            j=0; m=0; k=0; x=0; l=0;
            y2=60; x2=600;
            jButton3.setLocation(600,60); 
            t.stop(); 
            t2.stop();
            i++;
            if(ref<i)JOptionPane.showMessageDialog(null,"You missed it\nYou lost a life\n\nClick OK to continue");
            jButton1.doClick();
        }
        if(((x-x2)<2)&&((x-x2)>-45)&&((y-y2)<10)&&((y-y2)>-5)){
            i--;score+=5;n++;ref=i+1;
            jButton3.setLocation(600,60);
            jLabel6.setText(score+"");
            jButton1.doClick();
            JOptionPane.showMessageDialog(null,"That was great\nYou earned 5 coins\n\nClick OK to continue");
        }
        if(i==1)
            jLabel1.setIcon(new ImageIcon("F:\\Java Project\\src\\hrtc.png"));
        if(i==2)
            jLabel2.setIcon(new ImageIcon("F:\\Java Project\\src\\hrtc.png"));
        if(i==3){    
            jLabel3.setIcon(new ImageIcon("F:\\Java Project\\src\\hrtc.png"));
            jLabel7.setVisible(true);
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javaproject","root","mysql");
                Statement st = con.createStatement();
                String check = "select "+ difficulty[a] +" from birdhunt where username = '"+loginform.user+"';";
                ResultSet rs = st.executeQuery(check);
                rs.next();
                if(score>rs.getInt(1)){
                    String add = "update birdhunt set "+ difficulty[a] +" = "+score+" where username = '"+loginform.user+"';";
                    st.executeUpdate(add);
                }
            }
            catch(Exception E){
                System.out.print(E.getMessage());
            }
            t.stop();
            t2.stop();
            jButton5.setVisible(true);
            jButton7.setVisible(false);
            jButton6.setVisible(true);
        }
    }
};

t = new Timer(100, action);
t.setDelay(60);
t.setRepeats(true);
t.start();    

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jLabel1.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel2.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel3.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel8.setIcon(new ImageIcon("F:\\Java Project\\src\\coin.jpg"));
jLabel7.setVisible(false);
jButton5.setVisible(false);
jLabel6.setText(score+""); 
jButton3.setIcon(new ImageIcon("F:\\Java Project\\src\\bullet.jpg"));
jButton1.setIcon(new ImageIcon("F:\\Java Project\\src\\kuruvi.jpg"));
jButton7.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jLabel1.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel2.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel3.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel7.setVisible(false);  
i=0; j=0; m=0; k=0; score=0; n=0; ref=0;
x=0; y=0; y2=60; x2=600;
y1= r.nextInt(100);
jButton5.setVisible(false);
jButton2.setVisible(true);
jLabel6.setText(score+""); 
jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
a=0;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
a=1;       
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
a=2;     
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.setVisible(false);
new Shootthekuruvi().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
jButton3.setLocation(600,60);
t.stop();
t2.stop();
jLabel1.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel2.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel3.setIcon(new ImageIcon("F:\\Java Project\\src\\hrt.jpg"));
jLabel7.setVisible(false);  
i=0; j=0; m=0; k=0; score=0; n=0; ref=0; l=0;
x=0; y=0; y2=60; x2=600;
y1= r.nextInt(100);
jButton5.setVisible(false);
jButton2.setVisible(true);
jLabel6.setText(score+""); 
jPanel2.setVisible(true); 
jButton6.setVisible(true);
jButton7.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movebtnn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movebtnn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movebtnn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movebtnn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movebtnn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
