
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author krishnan
 */
public class Signupform extends javax.swing.JFrame {

    /**
     * Creates new form Signupform
     */
    public Signupform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sign up");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(149, 0, 173, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 61, 26);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 60, 147, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 120, 72, 26);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Confirm password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 170, 120, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/captcha.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 230, 179, 60);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 240, 80, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(100, 320, 147, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(140, 120, 147, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(140, 170, 147, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Enter the text given above");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 300, 168, 21);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/suback.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 480, 430);

        setBounds(0, 0, 424, 423);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int exist = 1;
String name = jTextField1.getText();
String password = new String(jPasswordField1.getPassword());
String conpassword = new String(jPasswordField2.getPassword());
String captcha =jTextField4.getText();
if(password.compareTo(conpassword)!=0)
    JOptionPane.showMessageDialog(this,"Please enter the same password in both the password fields");
else if(name.equals(""))
    JOptionPane.showMessageDialog(this,"Name has not been entered");
else if(password.equals(""))
    JOptionPane.showMessageDialog(this,"Password field is empty");
else if(captcha.equals(""))
    JOptionPane.showMessageDialog(this,"Captcha field is empty");
else if(captcha.compareTo("duBX8B")!=0)
    JOptionPane.showMessageDialog(this,"The captcha has been entered wrongly");
else{
    try{
        Class.forName("java.sql.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/javaproject","root","mysql");
        Statement st = con.createStatement();
        String check = "select * from userdata;";
        String include = "insert into userdata values('"+name+"','"+password+"',-1);";
        ResultSet rs = st.executeQuery(check);
        while(rs.next()){
            if(name.equals(rs.getString(1))){
                exist=0;
                JOptionPane.showMessageDialog(this,"This username already exists");
                break;
            }    
        }
        if(exist==1){
            st.executeUpdate(include);
            st.executeUpdate("insert into birdhunt values('"+name+"',0,0,0);");
            st.executeUpdate("insert into flappybird values('"+name+"',0);");
            this.setVisible(false);
            new loginform().setVisible(true);
        }
    }
    catch(Exception e){
        System.out.print(e.getMessage());
    }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signupform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signupform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
